In [ ]:
# Cargar la funcion especifica del paquete 
from numpy import arange

arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# Importar paquete con acrónimo
import numpy as np

A=np.arange(9)
A


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
type(A)

numpy.ndarray

In [16]:
A.mean() # np.mean(A)

np.float64(4.0)

In [18]:
A.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])