# Punto 1

In [2]:
import numpy as np 

numeros_primos = [2,3,4,5,7,11,13,17,19,23,29]
numeros_primos

[2, 3, 4, 5, 7, 11, 13, 17, 19, 23, 29]

In [4]:
array_primos=np.array(numeros_primos)
array_primos

array([ 2,  3,  4,  5,  7, 11, 13, 17, 19, 23, 29])

In [5]:
array_zeros=np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
array_numeros=np.arange(10)
array_numeros

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
array_pares=np.arange(0,20,2)
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
array_pares.reshape(2,5)
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# Punto 2

In [16]:
array_impares = array_pares + 1
array_impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [18]:
array_impares*100

array([ 100,  300,  500,  700,  900, 1100, 1300, 1500, 1700, 1900])

In [19]:
array_impares - array_pares

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [21]:
array_impares/array_pares

C:\Users\Lucci\AppData\Local\Temp\ipykernel_5704\2727502484.py:1: RuntimeWarning: divide by zero encountered in divide
  array_impares/array_pares


array([       inf, 1.5       , 1.25      , 1.16666667, 1.125     ,
       1.1       , 1.08333333, 1.07142857, 1.0625    , 1.05555556])

In [22]:
array_primos.sum()

np.int64(133)

In [30]:
array_primos.mean()

np.float64(12.090909090909092)

In [24]:
array_primos.var()

np.float64(73.17355371900827)

In [25]:
# declaramos un array con los numeros de Fibonacci
array_fibonacci = np.array([55, 0, 144, 1, 21, 89, 5, 8, 13, 1, 34, 3, 2])
array_fibonacci

array([ 55,   0, 144,   1,  21,  89,   5,   8,  13,   1,  34,   3,   2])

In [26]:
# Ordenamos de menor a mayor
np.sort(array_fibonacci)

array([  0,   1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144])

In [36]:
# Ordenamos de Mayor a Menor
np.sort(-array_fibonacci)

array([-144,  -89,  -55,  -34,  -21,  -13,   -8,   -5,   -3,   -2,   -1,
         -1,    0])

# Punto 3

---

In [38]:
# Como seleccionar un elemento
A = np.arange(0,20,2).reshape(2,5)
A

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [41]:
# Seleccionar un elemento en concreto -> 1 es la fila y 3 posición de columna
A[1,3]

np.int64(16)

In [44]:
# Seleccionar varios elementos por fila 
A[0,:]

array([0, 2, 4, 6, 8])

In [46]:
# Seleccionar elementos por Columna
A[:,2]

array([ 4, 14])

## Utilizar Filter

1. Condicion para menores de 20 

In [48]:
array_fibonacci<20 

array([False,  True, False,  True, False, False,  True,  True,  True,
        True, False,  True,  True])

2. Filtrar menores de 20

In [51]:
array_fibonacci[array_fibonacci<20] 

array([ 0,  1,  5,  8, 13,  1,  3,  2])